# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CurvedSplitAndMerge
                                 A QGIS plugin
 Helper to run split and merge on curved geometries
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-06-15
        copyright            : (C) 2020 by Opengis
        email                : olivier@opengis.ch
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CurvedSplitAndMerge class from file CurvedSplitAndMerge.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .curved_split_merge import CurvedSplitAndMerge
    return CurvedSplitAndMerge(iface)
