version: "3"

services:
  tests:
    image: opengisch/qgis:3.22.12-focal
    volumes:
      # mount the plugin
      - ./autocurve:/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/autocurve
      # include default config (enabling the plugin)
      - ./tests/QGIS3.ini:/root/.local/share/QGIS/QGIS3/profiles/default/QGIS/QGIS3.ini
      # mount the test folder
      - ./tests/tests_directory:/tests_directory
      # mount the x11 socket
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      DISPLAY: :0
    command: python3 /tests_directory/autocurve_tests.py
