on:
  pull_request:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Run tests
        run: docker-compose run tests
